# MyBatis和dataSource配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.130.68:3306/beacon_cloud?characterEncoding=utf-8&useSSL=false
    username: root
    password:  LuoYuRui123..!
    type: com.alibaba.druid.pool.DruidDataSource
# 服务名称
  application:
    name: beacon-webmaster
  # 多环境
  profiles:
    active: dev
  # nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 101.35.130.68:8848
      # nacos配置中心地址:
      config:
        server-addr: 101.35.130.68:8848
        file-extension: yml
        # beacon-webmaster-dev.yml

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# shiro配置
shiro:
  # 默认登录页面
  loginUrl: /login.html
  # 没有权限的页面
  unauthorizedUrl: unauthorized.html

